TEC-16773 Update search by vanityName to return instances according to primaryOrganizationType
ebx/ebx-linkedin-sdk pull request #157
Opened 2022-03-25 11:44 UTC by kennethwong-hc

### Description of Changes

- Add primaryOrganizationType in OrganizationBase
- Update findOrganizationByVanityName to return OrganizationBrand if primaryOrganizationType is BRAND

### Reference
https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?tabs=http

### Documentation
N/A

### Risks & Impacts
- Add support for organization brands

### Testing
- Modified LinkedInMetaInfo to use new version
```
    OrganizationBase normal = LinkedInMetaInfo.getPageInfoByVanityName(linkedInAPI,
        "Echobox");
    System.out.println(organizationToString(normal));
  
    OrganizationBase showcase = LinkedInMetaInfo.getPageInfoByVanityName(linkedInAPI,
        "bio-basketball-brand");
    System.out.println(organizationToString(showcase));
  
    OrganizationBase notFound = LinkedInMetaInfo.getPageInfoByVanityName(linkedInAPI,
        "news");
    System.out.println(organizationToString(notFound));
```
Print the type and data
```
  private static String organizationToString(OrganizationBase organization) {
    if (organization == null) {
      return "null";
    }
    StringBuilder sb = new StringBuilder();
    if (organization instanceof Organization) {
      Organization organization1 = (Organization) organization;
      sb.append("[Organization] - ");
      sb.append("vanityName: ").append(organization.getVanityName())
          .append(", primaryOrganizationType: ").append(organization.getPrimaryOrganizationType())
          .append(", locations: ").append(organization1.getLocations())
          .append(", organizationStatus: ").append(organization1.getOrganizationStatus())
          .append(", organizationType: ").append(organization1.getOrganizationType())
          .append(", deleted: ").append(organization1.getDeleted())
          .append(", entityStatus: ").append(organization1.getEntityStatus())
          .append(", groups: ").append(organization1.getGroups())
          .append(", localizedWebsite: ").append(organization1.getLocalizedWebsite())
          .append(", overviewPhotoV2: ").append(organization1.getOverviewPhotoV2())
          .append(", schoolAttributes: ").append(organization1.getSchoolAttributes())
          .append(", specialities: ").append(organization1.getSpecialties())
          .append(", staffCountRange: ").append(organization1.getStaffCountRange())
          .append(", alternativeNames: ").append(organization.getAlternativeNames())
          .append(", coverPhotoV2: ").append(organization.getCoverPhotoV2())
          .append(", defaultLocale: ").append(organization.getDefaultLocale())
          .append(", description: ").append(organization.getDescription())
          .append(", foundedOn: ").append(organization.getFoundedOn())
          .append(", id: ").append(organization.getId())
          .append(", industries: ").append(organization.getIndustries())
          .append(", localizedDescription: ").append(organization.getLocalizedDescription())
          .append(", localizedName: ").append(organization.getLocalizedName())
          .append(", logoV2: ").append(organization.getLogoV2())
          .append(", name: ").append(organization.getName())
          .append(", parentRelationship: ").append(organization.getParentRelationship())
          .append(", URN: ").append(organization.getUrn())
          .append(", versionTag: ").append(organization.getVersionTag())
          .append(", website: ").append(organization.getWebsite());
  
    } else if (organization instanceof OrganizationBrand) {
      OrganizationBrand organizationBrand = (OrganizationBrand) organization;
      sb.append("[OrganizationBrand] - ");
      sb.append("vanityName: ").append(organization.getVanityName())
          .append(", primaryOrganizationType: ").append(organization.getPrimaryOrganizationType())
          .append(", alternativeNames: ").append(organization.getAlternativeNames())
          .append(", coverPhotoV2: ").append(organization.getCoverPhotoV2())
          .append(", defaultLocale: ").append(organization.getDefaultLocale())
          .append(", description: ").append(organization.getDescription())
          .append(", foundedOn: ").append(organization.getFoundedOn())
          .append(", id: ").append(organization.getId())
          .append(", industries: ").append(organization.getIndustries())
          .append(", localizedDescription: ").append(organization.getLocalizedDescription())
          .append(", localizedName: ").append(organization.getLocalizedName())
          .append(", logoV2: ").append(organization.getLogoV2())
          .append(", name: ").append(organization.getName())
          .append(", parentRelationship: ").append(organization.getParentRelationship())
          .append(", URN: ").append(organization.getUrn())
          .append(", versionTag: ").append(organization.getVersionTag())
          .append(", website: ").append(organization.getWebsite())
          .append(", tags: ").append(organizationBrand.getTags())
          .append(", pinnedPost: ").append(organizationBrand.getPinnedPost())
          .append(", autoCreated: ").append(organizationBrand.getAutoCreated());
    }
    return sb.toString();
  }
```
Result:
```
[Organization] - vanityName: echoboxprimaryOrganizationType: NONE, locations: [com.echobox.api.linkedin.types.organization.LocationInfo@6869a3b3, com.echobox.api.linkedin.types.organization.LocationInfo@6ab4ba9f, com.echobox.api.linkedin.types.organization.LocationInfo@27ace0b1], organizationStatus: null, organizationType: null, deleted: null, entityStatus: null, groups: null, localizedWebsite: https://www.echobox.com, overviewPhotoV2: null, schoolAttributes: null, specialities: null, staffCountRange: null, alternativeNames: null, coverPhotoV2: null, defaultLocale: null, description: null, foundedOn: null, id: 5268030, industries: null, localizedDescription: null, localizedName: Echobox, logoV2: com.echobox.api.linkedin.types.organization.CroppedImage@664e5dee, name: com.echobox.api.linkedin.types.objectype.MultiLocaleString@431f1eaf, parentRelationship: null, URN: null, versionTag: null, website: null
[OrganizationBrand] - vanityName: bio-basketball-brandprimaryOrganizationType: BRAND, alternativeNames: null, coverPhotoV2: null, defaultLocale: null, description: null, foundedOn: null, id: 80927451, industries: null, localizedDescription: null, localizedName: bio basketball brand, logoV2: com.echobox.api.linkedin.types.organization.CroppedImage@470a659f, name: com.echobox.api.linkedin.types.objectype.MultiLocaleString@451882b2, parentRelationship: null, URN: null, versionTag: null, website: null, tags: null, pinnedPost: null, autoCreated: null
null
```

## Final Checklist

Please tick once completed.

- [ ] Build passes.
- [ ] Versioning considered (the version number in this PR is inline with semantic 
versioning requirements).
- [ ] Change log has been updated.

2022-03-28 09:16 UTC, djjashton requested changes
Looks good. I have one small question.

2022-03-28 09:16 UTC, djjashton commented on src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
> +    if (PrimaryOrganizationType.NONE.equals(targetType)) {
Should we provide some default logic for SCHOOL OrganizationType?

2022-03-29 07:17 UTC, djjashton approved these changes
Looks good

2022-03-29 08:25 UTC, kennethwong-hc commented
Over to @eddspencer for final review

2022-03-29 09:07 UTC, eddspencer requested changes
Thanks Kenneth just a couple of questions...

2022-03-29 16:23 UTC, kennethwong-hc commented on src/main/java/com/echobox/api/linkedin/connection/v2/OrganizationConnection.java
> +    PrimaryOrganizationType targetType = organizationList.get(0).getPrimaryOrganizationType();
Created a new class containing all fields from `Organization `and `OrganizationBrand `for deserialising. The instances in the result list will be created according to their `primaryOrganizationType`.
This also saves one endpoint call for organization brands.

2022-03-29 16:46 UTC, eddspencer requested changes
Thanks Kenneth - I think we may have one field missing....I was wondering whether the non-V2 fields should be included as well but I see that the [LinkedIn API docs](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/organizations/organization-lookup-api?tabs=http#organization) do not include these so probably fine to leave them out

2022-03-29 16:46 UTC, eddspencer commented on src/main/java/com/echobox/api/linkedin/types/organization/OrganizationResult.java
> +      organization.setOrganizationType(this.getOrganizationType());
What about `organizationStatus`?

2022-03-29 17:36 UTC, kennethwong-hc commented on src/main/java/com/echobox/api/linkedin/types/organization/OrganizationResult.java
> +      organization.setOrganizationType(this.getOrganizationType());
Good spot! Thanks.

2022-03-29 17:45 UTC, kennethwong-hc commented
Hi @eddspencer , yah, I think it is better to keep propagating those non-V2 fields, as it is an open-source SDK. It should be no harm if LinkedIn doesn't return those fields.
Besides, I added a unit test for the conversion. However, it is required to expose setUrn(). Do you know why we don't expose this setter? (this is the only field that doesn't have setter). The only reason I could think of is URN should be unchangeable, but id should be unchangeable as well ...

2022-03-30 07:26 UTC, eddspencer approved these changes
That looks great thanks Kenneth - no I was not part of the group that made the decision to not have a URN setter. However, I suspect you are right.....but by that logic you do not want to really change most of the fields so happy to have the URN setter existing.

2022-03-30 08:23 UTC, merged